# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OpenWRT 2 Mqtt add-on"
  org.opencontainers.image.description: "OpenWRT add-on to add openwrt information via mqtt."
  org.opencontainers.image.source: "https://github.com/hobbypunk90/homeassistant-addon-openwrt2mqtt"
  org.opencontainers.image.licenses: "Apache License 2.0"
