# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenWRT 2 MQTT
version: 2025.04.01
slug: openwrt2mqtt
description: OpenWRT add-on to add openwrt information via mqtt.
url: "https://github.com/hobbypunk90/homeassistant-addon-openwrt2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addon_config:rw
ports:
  3000/tcp: null
options:
  openwrt_url: ""
  openwrt_username: root
  openwrt_password: ""
  openwrt_latitude: null
  openwrt_longitude: null
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: mqtt
  mqtt_password: mqtt
  mqtt_retain: false
  debug: false
schema:
  openwrt_url: url
  openwrt_username: str?
  openwrt_password: password
  openwrt_latitude: float?
  openwrt_longitude: float?
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  mqtt_retain: bool?
  debug: bool?
