openwrt:
  url: ~
  username: ~
  password: ~
  latitude: ~
  longitude: ~
  sysupgrade:
    url: https://sysupgrade.openwrt.org/json/v1/overview.json
    attended: false
mqtt:
  host: ~
  port: 1883
  username: ~
  password: ~
  retain: true
  topics:
    discovery: homeassistant
    base: openwrt2mqtt
delete_unseen_after_days: 1
mac_resolver:
  url: https://www.macvendorlookup.com/
debug: false
version: dev
