openwrt:
  url: ~
  username: ~
  password: ~
  latitude: ~
  longitude: ~
mqtt:
  host: ~
  port: 1883
  username: ~
  password: ~
  retain: true
  topics:
    discovery: homeassistant
    base: openwrt2mqtt
delete_unseen_after_days: 1
mac_resolver:
  url: https://www.macvendorlookup.com/
debug: false
version: dev
