# frozen_string_literal: true

source "https://rubygems.org"

gem "mqtt", "~> 0.6.0"

gem "config", "~> 5.5"

gem "service_actor", "~> 4.0"

gem "faraday", "~> 2.12"

gem "activesupport", "~> 8.0"

gem "activemodel", "~> 8.0"
